In [2]:
import pandas as pd

In [3]:
#Question 1

boston_data = pd.read_csv("boston.csv")
boston_data

,Unnamed: 0,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,Price
0,0,0.00632,18.0,2.31,0.0,0.538,6.575,65.2,4.0900,1.0,296.0,15.3,396.90,4.98,24.0
1,1,0.02731,0.0,7.07,0.0,0.469,6.421,78.9,4.9671,2.0,242.0,17.8,396.90,9.14,21.6
2,2,0.02729,0.0,7.07,0.0,0.469,7.185,61.1,4.9671,2.0,242.0,17.8,392.83,4.03,34.7
3,3,0.03237,0.0,2.18,0.0,0.458,6.998,45.8,6.0622,3.0,222.0,18.7,394.63,2.94,33.4
4,4,0.06905,0.0,2.18,0.0,0.458,7.147,54.2,6.0622,3.0,222.0,18.7,396.90,5.33,36.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,501,0.06263,0.0,11.93,0.0,0.573,6.593,69.1,2.4786,1.0,273.0,21.0,391.99,9.67,22.4
502,502,0.04527,0.0,11.93,0.0,0.573,6.120,76.7,2.2875,1.0,273.0,21.0,396.90,9.08,20.6
503,503,0.06076,0.0,11.93,0.0,0.573,6.976,91.0,2.1675,1.0,273.0,21.0,396.90,5.64,23.9
504,504,0.10959,0.0,11.93,0.0,0.573,6.794,89.3,2.3889,1.0,273.0,21.0,393.45,6.48,22.0
505,505,0.04741,0.0,11.93,0.0,0.573,6.030,80.8,2.5050,1.0,273.0,21.0,396.90,7.88,11.9

In [4]:
print(boston_data.columns)

Index(['Unnamed: 0', 'CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS',
       'RAD', 'TAX', 'PTRATIO', 'B', 'LSTAT', 'Price'],
      dtype='object')

In [5]:
print(boston_data.corr())

            Unnamed: 0      CRIM        ZN     INDUS      CHAS       NOX  \
Unnamed: 0    1.000000  0.407407 -0.103393  0.399439 -0.003759  0.398736
CRIM          0.407407  1.000000 -0.200469  0.406583 -0.055892  0.420972
ZN           -0.103393 -0.200469  1.000000 -0.533828 -0.042697 -0.516604
INDUS         0.399439  0.406583 -0.533828  1.000000  0.062938  0.763651
CHAS         -0.003759 -0.055892 -0.042697  0.062938  1.000000  0.091203
NOX           0.398736  0.420972 -0.516604  0.763651  0.091203  1.000000
RM           -0.079971 -0.219247  0.311991 -0.391676  0.091251 -0.302188
AGE           0.203784  0.352734 -0.569537  0.644779  0.086518  0.731470
DIS          -0.302211 -0.379670  0.664408 -0.708027 -0.099176 -0.769230
RAD           0.686002  0.625505 -0.311948  0.595129 -0.007368  0.611441
TAX           0.666626  0.582764 -0.314563  0.720760 -0.035587  0.668023
PTRATIO       0.291074  0.289946 -0.391679  0.383248 -0.121515  0.188933
B            -0.295041 -0.385064  0.175520 -0.356977  0.048788 -0.380051
LSTAT         0.258465  0.455621 -0.412995  0.603800 -0.053929  0.590879
Price        -0.226604 -0.388305  0.360445 -0.483725  0.175260 -0.427321

                  RM       AGE       DIS       RAD       TAX   PTRATIO  \
Unnamed: 0 -0.079971  0.203784 -0.302211  0.686002  0.666626  0.291074
CRIM       -0.219247  0.352734 -0.379670  0.625505  0.582764  0.289946
ZN          0.311991 -0.569537  0.664408 -0.311948 -0.314563 -0.391679
INDUS      -0.391676  0.644779 -0.708027  0.595129  0.720760  0.383248
CHAS        0.091251  0.086518 -0.099176 -0.007368 -0.035587 -0.121515
NOX        -0.302188  0.731470 -0.769230  0.611441  0.668023  0.188933
RM          1.000000 -0.240265  0.205246 -0.209847 -0.292048 -0.355501
AGE        -0.240265  1.000000 -0.747881  0.456022  0.506456  0.261515
DIS         0.205246 -0.747881  1.000000 -0.494588 -0.534432 -0.232471
RAD        -0.209847  0.456022 -0.494588  1.000000  0.910228  0.464741
TAX        -0.292048  0.506456 -0.534432  0.910228  1.000000  0.460853
PTRATIO    -0.355501  0.261515 -0.232471  0.464741  0.460853  1.000000
B           0.128069 -0.273534  0.291512 -0.444413 -0.441808 -0.177383
LSTAT      -0.613808  0.602339 -0.496996  0.488676  0.543993  0.374044
Price       0.695360 -0.376955  0.249929 -0.381626 -0.468536 -0.507787

                   B     LSTAT     Price
Unnamed: 0 -0.295041  0.258465 -0.226604
CRIM       -0.385064  0.455621 -0.388305
ZN          0.175520 -0.412995  0.360445
INDUS      -0.356977  0.603800 -0.483725
CHAS        0.048788 -0.053929  0.175260
NOX        -0.380051  0.590879 -0.427321
RM          0.128069 -0.613808  0.695360
AGE        -0.273534  0.602339 -0.376955
DIS         0.291512 -0.496996  0.249929
RAD        -0.444413  0.488676 -0.381626
TAX        -0.441808  0.543993 -0.468536
PTRATIO    -0.177383  0.374044 -0.507787
B           1.000000 -0.366087  0.333461
LSTAT      -0.366087  1.000000 -0.737663
Price       0.333461 -0.737663  1.000000

In [6]:
#Question 2

import os, ssl 
if (not os.environ.get('PYTHONHTTPSVERIFY', '') and getattr(ssl, '_create_unverified_context', None)):
    ssl._create_default_https_context = ssl._create_unverified_context

from sklearn.datasets import fetch_california_housing
house = fetch_california_housing()

print(house.data.shape)
print(house.feature_names)

hou = pd.DataFrame(house.data, columns = house.feature_names)
hou

(20640, 8)
['MedInc', 'HouseAge', 'AveRooms', 'AveBedrms', 'Population', 'AveOccup', 'Latitude', 'Longitude']

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25
...,...,...,...,...,...,...,...,...
20635,1.5603,25.0,5.045455,1.133333,845.0,2.560606,39.48,-121.09
20636,2.5568,18.0,6.114035,1.315789,356.0,3.122807,39.49,-121.21
20637,1.7000,17.0,5.205543,1.120092,1007.0,2.325635,39.43,-121.22
20638,1.8672,18.0,5.329513,1.171920,741.0,2.123209,39.43,-121.32
20639,2.3886,16.0,5.254717,1.162264,1387.0,2.616981,39.37,-121.24

In [14]:
import numpy as np
from sklearn.preprocessing import MinMaxScaler, StandardScaler

range = (0, 10)
scaler = MinMaxScaler(feature_range=range)
minmaxnormal = scaler.fit_transform(hou)
print("Original:")
print(hou)
print("MinMax Normalized:")
print(minmaxnormal)
scaler = StandardScaler()
std_normal = scaler.fit_transform(hou)
print("StandardScaler Normalized: ")
print(std_normal)

Original:
       MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0      8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88
1      8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86
2      7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85
3      5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85
4      3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85
...       ...       ...       ...        ...         ...       ...       ...
20635  1.5603      25.0  5.045455   1.133333       845.0  2.560606     39.48
20636  2.5568      18.0  6.114035   1.315789       356.0  3.122807     39.49
20637  1.7000      17.0  5.205543   1.120092      1007.0  2.325635     39.43
20638  1.8672      18.0  5.329513   1.171920       741.0  2.123209     39.43
20639  2.3886      16.0  5.254717   1.162264      1387.0  2.616981     39.37

       Longitude
0        -122.23
1        -122.22
2        -122.24
3        -122.25
4        -122.25
...          ...
20635    -121.09
20636    -121.21
20637    -121.22
20638    -121.32
20639    -121.24

[20640 rows x 8 columns]
MinMax Normalized:
[[ 5.39668418  7.84313725  0.43512302 ...  0.01499426  5.67481403
   2.11155378]
 [ 5.38027062  3.92156863  0.38223954 ...  0.01140743  5.65356004
   2.12151394]
 [ 4.66028055 10.          0.52756464 ...  0.01697958  5.64293305
   2.10159363]
 ...
 [ 0.82764376  3.1372549   0.30903857 ...  0.013144    7.32199787
   3.11752988]
 [ 0.94295251  3.33333333  0.31782686 ...  0.011515    7.32199787
   3.01792829]
 [ 1.30253376  2.94117647  0.31252455 ...  0.01548857  7.25823592
   3.09760956]]
StandardScaler Normalized:
[[ 2.34476576  0.98214266  0.62855945 ... -0.04959654  1.05254828
  -1.32783522]
 [ 2.33223796 -0.60701891  0.32704136 ... -0.09251223  1.04318455
  -1.32284391]
 [ 1.7826994   1.85618152  1.15562047 ... -0.02584253  1.03850269
  -1.33282653]
 ...
 [-1.14259331 -0.92485123 -0.09031802 ... -0.0717345   1.77823747
  -0.8237132 ]
 [-1.05458292 -0.84539315 -0.04021111 ... -0.09122515  1.77823747
  -0.87362627]
 [-0.78012947 -1.00430931 -0.07044252 ... -0.04368215  1.75014627
  -0.83369581]]